name: Azure environment for project
on:
  push:
    paths: 
      [ .github/workflows/azure_delete_project.yaml ]

jobs:
  create_rg:
    name: Delete Azure Resource Group and SPN
    runs-on: ubuntu-latest
    env:
      resource_group_name: "test-rg" 
      project_name:  "test-azure-access"

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Azure ResourceGroup
        uses: azure/CLI@v1
        with:
          inlineScript: |
            spn_name='${{ env.project_name }}-spn'
            spjson=$(az keyvault secret show -n $spn_name --vault-name kv-projectgene)

            # retrive the spn from Azure keyvault
            echo "$spjson"
            spn=$(echo "$spjson" | jq '.value' -r | jq '.clientId' -r)
 
            # clean up - remove spn, resource group and the Keyvault Secret
            az group delete --name ${{env.resource_group_name }} --yes 
            az ad sp delete --id "$spn"
            az keyvault secret delete -n $spn_name --vault-name kv-projectgene
