name: Azure environment for project
on:
  push:
    paths: 
      [ .github/workflows/azure_delete_project.yaml ]

jobs:
  create_rg:
    name: Delete Azure Resource Group and SPN
    runs-on: ubuntu-latest
    env:
      resource_group_name: "test-azure-access" 
      project_name:  "test-azure-access"

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Azure Resources
        uses: azure/CLI@v1
        with:
          inlineScript: |
            gitkv=$(az keyvault secret show -n $spn_name --vault-name kv-tesrg --query value)
            gitkvjson=$(echo "$gitkv" | tr -d '\"'| base64 -d)

            # retrive the spn from Azure keyvault
            echo "$spjson"
            spn=$(echo "$gitkvjson" | jq '.value' -r | jq '.clientId' -r)
            echo $spn
 
            # clean up - remove spn, resource group and the Keyvault Secret
            
            az group delete --name ${{env.resource_group_name }} --yes 
            
            az ad sp delete --id $spn
            
            spn_name='${{ env.project_name }}-spn'
            az keyvault secret delete -n $spn_name --vault-name "kv-tesrg"
