# https://help.github.com/en/actions 
# Work flow using Azure CLI to create project environment on Azure


name: Azure environment for project
on:
  push:
    paths: 
      [ .github/workflows/azure-config.yaml ]

jobs:
  create_rg:
    name: Create Azure Resource Group 
    runs-on: ubuntu-latest
    env:
      resource_group_name: "test3-rg" 
      azure_region: "southIndia"
      resource_group_id: "test"
      project_name: "project_xxx" 

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      ### Create Azure Resource Group and SPN with access to RG
      
      - name: Create Azure ResourceGroup
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -n ${{ env.resource_group_name }}  --location ${{ env.azure_region }}
            resourceGroupId=`az group show -n ${{ env.resource_group_name }}  --query id`
            ## remove quotes in resourceGroupId 
            temp="${resourceGroupId%\"}"
            rgId="${temp#\"}"
            echo $rgId
            ### update the environment variable with Resource Group ID
            # {{ env.resource_group_id  }}=$rgId  (this is not working)
            
            ### Create Azure AD service principal with Contributor role to the resource group
            spnName='${{env.resource_group_name }}_${{ env.project_name }}_spn'
            az ad sp create-for-rbac --name $spnName --role Contributor --scope $rgId > $GITHUB_WORKSPACE/spn.json
            cat $GITHUB_WORKSPACE/spn.json
#  Create the JSON file for Github secret
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: update permissions to the script
        run: chmod +x $GITHUB_WORKSPACE/src/create_json.sh
      - name: run the script
        run: $GITHUB_WORKSPACE/src/create_json $GITHUB_WORKSPACE/spn.json   
      - name: show the file
        run: echo ./github-secret.json
