name: Azure environment for project
on:
  push:
    paths: 
      [ .github/workflows/azure_delete_project.yaml ]

jobs:
  create_rg:
    name: Delete Azure Resource Group and SPN
    runs-on: ubuntu-latest
    env:
      resource_group_name: "test-azure-access" 

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Delete Azure Resources
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # retrive the spn from Azure keyvault
            spn_name=${{ env.resource_group_name }}-spn
            gitkv=$(az keyvault secret show --name $spn_name --vault-name "kv-tesrg" --query value)
            gitkvjson=$(echo "$gitkv" | tr -d '\"'| base64 -d)

            # retrive the spn id from the Keyvault JSON
            #echo "$spjson"
            spn=$(echo "$gitkvjson" | jq '.clientId' -r)
            #echo $spn
 
            # clean up - remove spn, resource group and the Keyvault Secret
            rg_name=${{env.resource_group_name }}
            az group delete --name $rg_name --yes --no-wait
            
            az ad sp delete --id $spn
            
            az keyvault secret delete --name "$spn_name" --vault-name "kv-tesrg"
