name: Azure environment for project
on:
  push:
    paths: 
      [ .github/workflows/azure_delete_project.yaml ]

jobs:
  create_rg:
    name: Create Azure Resource Group 
    runs-on: ubuntu-latest
    env:
      resource_group_name: "test-rg" 
      project_spn: "3ba010f3-64b5-47d9-956e-af633cedcc33"  

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Azure ResourceGroup
        uses: azure/CLI@v1
        with:
          inlineScript: |
            
            #account details in json format
            accjson=$(az account show)
            # clean up - remove spn and resource group
            az ad sp delete --id ${{ env.project_spn }}
            az group delete --name ${{env.resource_group_name }} --yes --no-wait
